### PR TITLE
Spanish remaning web translation a a few URL corrections on sidebar ( missed es/ )

### PR DESCRIPTION
**Pull request by jpuigs**

### CODE REVIEW

**Comment by jpuigs** [comment]
Spanish is finished.
Now I'll translate website to catalan.

**Comment by shaxxx** [comment]
Site is alive on krkadoni.com so you can check for any potential errors.
Regards.

**Comment by jpuigs** [comment]
Yes I know.
I've seen the wrong spanish URLs  there...... 😄 (because they switched to english)

**Comment by shaxxx** [comment]
New build with your translations is ready for download from build server. If you're using iOS send me your e-mail on PM and I'll add you to TestFlight program.

https://shax.visualstudio.com/SignalMeter/_build/results?buildId=304&view=artifacts&type=publishedArtifacts

**Comment by jpuigs** [comment]
No, I have a Samsung Galaxy S8.

**Comment by shaxxx** [comment]
Great, then you can try it right now, you dont  need to wait.

**Pull request merged**
